#!/usr/bin/env python3
import sys


def solve(S: str):

    T = ""
    count = 0
    direction = True

    for i in S:
        if i == "R":
            count += 1
            direction = not direction
        elif not T:
            T = i
        elif direction:
            if T[-1] == i:
                T = T[:-1]
            else:
                T += i
        else:
            if T[0] == i:
                T = T[1:]
            else:
                T = i + T

    if not direction:
        T = T[::-1]

    print(T)

    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)


if __name__ == '__main__':
    main()
