#!/usr/bin/env python3
import sys


def solve(N: int, K: int, AB: "List[int]"):

    k = K
    for ab in AB:
        if k < ab[0]:
            print(k)
            return
        else:
            k += ab[1]

    print(k)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    input = sys.stdin.readline

    N, K = map(int, input().split())  # type: int
    AB = [list(map(int, input().split())) for _ in range(N)]
    solve(N, K, sorted(AB))


if __name__ == '__main__':
    main()
