#!/usr/bin/env python3
import sys


def count_01(t):
    count = 0
    for i in t:
        if i == '1':
            count += 1
        else:
            count -= 1
        if count < 0:
            return False
    return True


def solve(N: int):

    if N % 2:
        print()
    else:
        s = 2**(N-1)
        a = 2**N-1
        for i in range(a, s-1, -1):
            t = format(i, 'b')
            if t.count('1') == t.count('0') and count_01(t):
                t = t.replace('0', ')')
                t = t.replace('1', '(')
                print(t)

    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
