#!/usr/bin/env python3
import sys


def gcd(x, y):
    if not x or not y:
        return max(x, y)

    else:
        if x > y:
            return gcd(x % y, y)
        else:
            return gcd(x, y % x)


def solve(A: int, B: int):

    for c in range(B, 0, -1):
        if -(-A//c) < B//c:
            print(c)
            return

    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)


if __name__ == '__main__':
    main()
