#!/usr/bin/env python3
import sys


def solve(N: int):

    l = len(str(N))
    comma = l//3
    count = 0
    for i in range(1, comma+1):
        if comma == i:
            pass
        else:
            count += 10**(3*i)
            print(count)

    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
