#!/usr/bin/env python3
import sys
import math

def lcm(x, y):
    return (x * y) // math.gcd(x, y)

def solve(N: int, A: int, B: int):
    
    a = N//A
    b = N//B
    ab = N//lcm(A, B)
    
    sum_a = (a * (a + 1) // 2) * A
    sum_b = (b * (b + 1) // 2) * B
    sum_ab = (ab * (ab + 1) // 2) * lcm(A, B)

    sum_n = N * (N + 1) // 2
    
    print(sum_n - (sum_a + sum_b - sum_ab))
    
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(N, A, B)

if __name__ == '__main__':
    main()
