import sys

low = 'Yay!'
eq = 'so-so'
high = ':('


def solve(N: int):

    x = int(N * 1.08)

    if x < 206:
        print(low)
    elif x > 206:
        print(high)
    else:
        print(eq)

    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
