#!/usr/bin/env python3
import sys


def solve(N: int, K: int):

    v = 0
    for n in range(1, N+1):
        for k in range(1, K+1):
            v += int(str(n)+'0'+str(k))

    print(v)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)


if __name__ == '__main__':
    main()
