#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(A: "List[int]"):
    a = sorted(A)

    diff = a[1] - a[0]
    for i in range(1, len(A)-1):
        if a[i+1] - a[i] != diff:
            print(NO)
            return
        else:
            diff = a[i+1]-a[i]

    print(YES)

    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = [int(next(tokens)) for _ in range(3)]  # type: "List[int]"
    solve(A)


if __name__ == '__main__':
    main()
