#!/usr/bin/env python3
import sys


def solve(S: str, a: int, b: int):

    first = S[:a-1]
    middle = S[a:b-1]
    last = S[b:]

    print(first+S[b-1]+middle+S[a-1]+last)

    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    solve(S, a, b)


if __name__ == '__main__':
    main()
