#!/usr/bin/env python3
import sys
import math


def solve(A: int, B: int, W: int):

    _max = int(math.floor(1000*W/A))
    _min = int(math.ceil(1000*W/B))

    if _min > _max:
        print('UNSATISFIABLE')
    else:
        print(_min, _max)

    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    solve(A, B, W)


if __name__ == '__main__':
    main()
